"use client";

import { useEffect, useState, useRef, useMemo } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { ArrowLeft, Loader2, Check, ArrowRight } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import { UpgradeModal } from "@/components/dashboard/UpgradeModal";
import type { AuthenticatedUser, ConnectionStatus, AutomationSetupField } from "@/lib/automation";

type WorkflowResponse = {
  workflow: {
    name: string;
    description: string;
    trigger: string;
    steps: Array<{
      type: string;
      name: string;
      details: Record<string, string>;
    }>;
    integrations: string[];
    requiredFields: string[];
    setupFields: AutomationSetupField[];
  };
  fieldDefinitions: AutomationSetupField[];
  source: "openai" | "fallback";
};

type IntegrationState = Record<string, ConnectionStatus>;

export default function SetupEngine({ user }: { user: AuthenticatedUser }) {
  const searchParams = useSearchParams();
  const router = useRouter();
  const initialPrompt = searchParams.get("prompt") || "";
  
  const [isGenerating, setIsGenerating] = useState(true);
  const [isActivating, setIsActivating] = useState(false);
  const [result, setResult] = useState<WorkflowResponse | null>(null);
  const [fieldValues, setFieldValues] = useState<Record<string, string>>({});
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [integrationStatus, setIntegrationStatus] = useState<IntegrationState>({});
  const [connectionLoading, setConnectionLoading] = useState<string | null>(null);
  const [globalError, setGlobalError] = useState<string | null>(null);
  const [showUpgradeModal, setShowUpgradeModal] = useState(false);
  
  const hasAutoGeneratedRef = useRef(false);
  const formRef = useRef<HTMLDivElement>(null);
  const inputRefs = useRef<(HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | null)[]>([]);

  // Preload Integrations
  useEffect(() => {
    const loadConnections = async () => {
      try {
        const response = await fetch("/api/integrations", { cache: "no-store" });
        if (!response.ok) return;
        const json = await response.json();
        const nextStatus: IntegrationState = {};
        (json.integrations ?? []).forEach((integration: any) => {
          nextStatus[integration.integration] = integration.status;
        });
        setIntegrationStatus(nextStatus);
      } catch {
        // Silent catch
      }
    };
    void loadConnections();
  }, []);

  // Initialize form fields when result loads
  useEffect(() => {
    if (!result) return;
    const initialValues: Record<string, string> = {};
    result.fieldDefinitions.forEach((field) => {
      initialValues[field.key] = field.type === "select" ? field.options?.[0] || "" : "";
    });
    setFieldValues(initialValues);
    setFieldErrors({});
    
    // Auto-focus first input after render
    setTimeout(() => {
      if (inputRefs.current[0]) {
        inputRefs.current[0].focus();
      }
    }, 100);
  }, [result]);

  // Execute Generation automatically on load
  useEffect(() => {
    if (!initialPrompt || hasAutoGeneratedRef.current) return;
    hasAutoGeneratedRef.current = true;
    
    const generate = async () => {
      setIsGenerating(true);
      setGlobalError(null);
      try {
        const response = await fetch("/api/generate-automation", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt: initialPrompt }),
        });

        if (response.status === 402) {
          setShowUpgradeModal(true);
          return;
        }

        const json = await response.json();
        if (!response.ok) throw new Error(json.error || "Generation failed.");
        
        setResult(json as WorkflowResponse);
        // Replace URL state to clean it up visually if desired, but retaining it is fine.
      } catch (err) {
        setGlobalError(err instanceof Error ? err.message : "Could not generate automation");
      } finally {
        setIsGenerating(false);
      }
    };

    void generate();
  }, [initialPrompt]);

  const handleConnectIntegration = async (integration: string) => {
    setConnectionLoading(integration);
    try {
      const response = await fetch("/api/integrations/connect", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ integration }),
      });
      const json = await response.json();
      if (!response.ok || !json.connection) throw new Error(json.error || "Could not connect.");
      setIntegrationStatus((current) => ({
        ...current,
        [json.connection.integration]: json.connection.status,
      }));
    } catch {
      // In a real flow, a popup for OAuth opens. For now, simulate success if error hits or set disconnected
    } finally {
      setConnectionLoading(null);
    }
  };

  const validateForm = () => {
    if (!result) return false;
    let isValid = true;
    const newErrors: Record<string, string> = {};

    result.fieldDefinitions.forEach(field => {
      const val = fieldValues[field.key] || "";
      // Assume all required for this strict app flow unless specified otherwise
      if (!val.trim()) {
        newErrors[field.key] = "This field is required";
        isValid = false;
      }
    });

    setFieldErrors(newErrors);
    return isValid;
  };

  const handleActivate = async () => {
    if (!result || !validateForm()) return;
    
    // Check if all integrations are strictly connected
    const unconnected = result.workflow.integrations.find(i => integrationStatus[i] !== "connected");
    if (unconnected) {
      setGlobalError(`Please connect ${unconnected} before activating`);
      return;
    }

    setIsActivating(true);
    setGlobalError(null);

    try {
      const relevantIntegrationStatus = Object.fromEntries(
        result.workflow.integrations.map((i) => [i, integrationStatus[i] || "disconnected"])
      );
      
      const response = await fetch("/api/save-automation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          workflow: result.workflow,
          formInputs: fieldValues,
          integrationStatus: relevantIntegrationStatus,
        }),
      });
      
      const json = await response.json();
      if (!response.ok || !json.automation) throw new Error(json.error || "Could not activate.");
      
      // Success, smooth transition to dashboard
      // We can add a brief artificial delay to make the success state feel substantial
      await new Promise(res => setTimeout(res, 500));
      router.push("/dashboard");
    } catch (err) {
      setGlobalError(err instanceof Error ? err.message : "Failed to activate automation.");
      setIsActivating(false);
    }
  };

  const allIntegrationsConnected = useMemo(() => {
    if (!result || result.workflow.integrations.length === 0) return true;
    return result.workflow.integrations.every((i) => integrationStatus[i] === "connected");
  }, [integrationStatus, result]);

  const handleKeyDown = (e: React.KeyboardEvent, index: number) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      const nextInput = inputRefs.current[index + 1];
      if (nextInput) {
        nextInput.focus();
        nextInput.scrollIntoView({ behavior: "smooth", block: "center" });
      } else {
        // Reached end, try submit
        void handleActivate();
      }
    }
  };

  return (
    <div className="min-h-screen bg-white selection:bg-[#111111] selection:text-white">
      {/* Top Section */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-black/[0.04]">
        <div className="mx-auto flex max-w-[720px] items-center justify-between px-6 py-4">
          <button 
            onClick={() => router.back()}
            className="flex items-center gap-2 text-sm font-medium text-[#111111]/50 hover:text-[#111111] transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back
          </button>
          
          <span className="text-sm font-semibold text-[#111111]">
            Setup your automation
          </span>
          
          <span className="text-sm font-medium text-[#111111]/40">
            Step 2 of 2
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-[720px] px-6 pt-32 pb-32">
        <AnimatePresence mode="wait">
          {isGenerating ? (
            <motion.div
              key="loading"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="flex flex-col items-center justify-center py-24 text-center"
            >
              <div className="relative mb-6 flex h-16 w-16 items-center justify-center">
                <Loader2 className="h-8 w-8 animate-spin text-[#111111]/40" />
              </div>
              <h2 className="text-xl font-medium tracking-tight text-[#111111]">
                Analyzing workflow...
              </h2>
              <p className="mt-2 text-sm text-[#111111]/50">
                Designing the optimal setup form for your automation.
              </p>
            </motion.div>
          ) : globalError && !result ? (
            <motion.div
              key="error"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="rounded-2xl border border-red-100 bg-red-50 p-6 text-center"
            >
              <p className="font-medium text-red-600">{globalError}</p>
              <button 
                onClick={() => router.back()}
                className="mt-4 px-4 py-2 rounded-full bg-white border border-red-200 text-sm font-medium text-red-600 shadow-sm"
              >
                Go Back
              </button>
            </motion.div>
          ) : result ? (
            <motion.div
              key="content"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            >
              {/* Automation Summary Card */}
              <div className="mb-12 rounded-[24px] border border-black/[0.06] bg-white p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
                <h3 className="mb-6 text-xs font-bold uppercase tracking-[0.16em] text-[#111111]/40">
                  Automation Preview
                </h3>
                
                <div className="flex flex-col gap-6">
                  <div>
                    <span className="text-sm font-semibold text-[#111111]">Triggered when:</span>
                    <p className="mt-1 text-[#111111]/70 leading-relaxed">
                      {result.workflow.trigger}
                    </p>
                  </div>
                  
                  <div className="h-px bg-black/[0.04] w-full" />
                  
                  <div>
                    <span className="text-sm font-semibold text-[#111111]">Actions:</span>
                    <ul className="mt-3 flex flex-col gap-3">
                      {result.workflow.steps.map((step, idx) => (
                        <li key={idx} className="flex items-start gap-3 text-[#111111]/70">
                          <Check className="h-4 w-4 mt-0.5 shrink-0 text-[#111111]/30" />
                          <span className="leading-relaxed">{step.name}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>

              {/* Form Section */}
              <div ref={formRef}>
                <div className="mb-8">
                  <h2 className="text-2xl font-semibold tracking-tight text-[#111111]">
                    Complete setup
                  </h2>
                  <p className="mt-2 text-[0.95rem] text-[#111111]/60">
                    Add the required details to activate your automation lock-in.
                  </p>
                </div>

                {/* Sub-section: Integrations (if any) */}
                {result.workflow.integrations.length > 0 && (
                  <div className="mb-10">
                    <p className="mb-4 text-xs font-bold uppercase tracking-[0.1em] text-[#111111]/40">
                      Required Accounts
                    </p>
                    <div className="grid gap-3 sm:grid-cols-2">
                      {result.workflow.integrations.map((integration) => {
                        const isConnected = integrationStatus[integration] === "connected";
                        const isLoading = connectionLoading === integration;
                        
                        return (
                          <div key={integration} className="flex items-center justify-between rounded-2xl border border-black/[0.08] p-4 bg-[#f8f9fb]">
                            <span className="font-medium capitalize text-[#111111]">{integration}</span>
                            <button
                              onClick={() => handleConnectIntegration(integration)}
                              disabled={isConnected || isLoading}
                              className={`text-sm font-semibold transition-colors ${
                                isConnected ? "text-emerald-600" : "text-[#3B82F6] hover:text-[#2563EB]"
                              } disabled:opacity-50`}
                            >
                              {isLoading ? "Connecting..." : isConnected ? "Connected" : "Connect →"}
                            </button>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                {/* Sub-section: Fields grid */}
                <div className="grid gap-x-6 gap-y-8 sm:grid-cols-2">
                  {result.fieldDefinitions.map((field, index) => {
                    const isFullWidthArea = field.type === "textarea";
                    const hasError = !!fieldErrors[field.key];

                    const inputClass = `w-full rounded-[14px] border ${
                      hasError ? "border-red-500/50 bg-red-50/50" : "border-black/[0.06] bg-[#f8f9fb]"
                    } px-4 py-3.5 text-[0.95rem] text-[#111111] placeholder:text-[#111111]/30 outline-none transition-all duration-200 focus:border-[#111111] focus:bg-white focus:ring-1 focus:ring-[#111111]`;

                    return (
                      <motion.div 
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.4, delay: 0.1 + index * 0.05 }}
                        key={field.key} 
                        className={isFullWidthArea ? "sm:col-span-2" : "col-span-1"}
                      >
                        <label className="mb-2 block text-sm font-medium text-[#111111]">
                          {field.label}
                        </label>
                        
                        {field.type === "textarea" ? (
                          <textarea
                            rows={3}
                            ref={(el) => { inputRefs.current[index] = el; }}
                            value={fieldValues[field.key] || ""}
                            onChange={(e) => {
                              setFieldValues(c => ({...c, [field.key]: e.target.value}));
                              if (hasError) setFieldErrors(e => ({...e, [field.key]: ""}));
                            }}
                            onKeyDown={(e) => handleKeyDown(e, index)}
                            placeholder={field.placeholder}
                            className={`${inputClass} resize-none`}
                          />
                        ) : field.type === "select" ? (
                          <select
                            ref={(el) => { inputRefs.current[index] = el; }}
                            value={fieldValues[field.key] || field.options?.[0] || ""}
                            onChange={(e) => {
                              setFieldValues(c => ({...c, [field.key]: e.target.value}));
                              if (hasError) setFieldErrors(e => ({...e, [field.key]: ""}));
                            }}
                            onKeyDown={(e) => handleKeyDown(e, index)}
                            className={inputClass}
                            style={{ appearance: 'none' }} // to keep it supremely minimal
                          >
                            {(field.options || []).map((opt) => (
                              <option key={opt} value={opt}>{opt}</option>
                            ))}
                          </select>
                        ) : (
                          <input
                            type={field.type === "phone" ? "tel" : field.type === "email" ? "email" : "text"}
                            ref={(el) => { inputRefs.current[index] = el; }}
                            value={fieldValues[field.key] || ""}
                            onChange={(e) => {
                              setFieldValues(c => ({...c, [field.key]: e.target.value}));
                              if (hasError) setFieldErrors(e => ({...e, [field.key]: ""}));
                            }}
                            onKeyDown={(e) => handleKeyDown(e, index)}
                            placeholder={field.placeholder}
                            className={inputClass}
                          />
                        )}

                        <AnimatePresence>
                          {hasError && (
                            <motion.p
                              initial={{ opacity: 0, height: 0 }}
                              animate={{ opacity: 1, height: 'auto', marginTop: 8 }}
                              exit={{ opacity: 0, height: 0, marginTop: 0 }}
                              className="text-[0.8rem] font-medium text-red-500"
                            >
                              {fieldErrors[field.key]}
                            </motion.p>
                          )}
                        </AnimatePresence>
                      </motion.div>
                    );
                  })}
                </div>

                {globalError && (
                  <div className="mt-8 rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm font-medium text-red-600">
                    {globalError}
                  </div>
                )}
              </div>
            </motion.div>
          ) : null}
        </AnimatePresence>
      </main>

      {/* Sticky Bottom Actions */}
      {result && !isGenerating && (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="fixed bottom-0 left-0 right-0 z-50 bg-gradient-to-t from-white via-white to-transparent pb-8 pt-10"
        >
          <div className="mx-auto max-w-[720px] px-6">
            <button
              onClick={() => void handleActivate()}
              disabled={isActivating || !allIntegrationsConnected}
              className={`group relative flex h-[60px] w-full items-center justify-center gap-3 overflow-hidden rounded-full font-semibold transition-all duration-300 ${
                isActivating 
                  ? "bg-[#111111] text-white opacity-90 cursor-not-allowed scale-[0.99]"
                  : !allIntegrationsConnected
                  ? "bg-[#f3f4f6] text-[#111111]/40 cursor-not-allowed"
                  : "bg-[#111111] text-white shadow-[0_8px_30px_rgba(0,0,0,0.12)] hover:-translate-y-1 hover:shadow-[0_12px_40px_rgba(0,0,0,0.2)]"
              }`}
            >
              <div className="absolute inset-0 flex items-center justify-center bg-white/10 opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
              {isActivating ? (
                <>
                  <Loader2 className="h-5 w-5 animate-spin" />
                  Creating automation...
                </>
              ) : !allIntegrationsConnected ? (
                "Connect Required Apps to Activate"
              ) : (
                <>
                  Activate Automation
                  <ArrowRight className="h-5 w-5 transition-transform duration-300 group-hover:translate-x-1" />
                </>
              )}
            </button>
          </div>
        </motion.div>
      )}

      <UpgradeModal isOpen={showUpgradeModal} onClose={() => setShowUpgradeModal(false)} />
    </div>
  );
}
