"use client";

import Link from "next/link";
import {
  useEffect,
  useEffectEvent,
  useMemo,
  useRef,
  useState,
} from "react";
import { useSearchParams } from "next/navigation";
import { motion, useScroll, useSpring, useTransform } from "framer-motion";
import { ArrowRight, ChevronRight, Sparkles } from "lucide-react";
import HeroScene from "@/components/HeroScene";
import HomeAutomationPreview from "@/components/home/HomeAutomationPreview";
import type {
  AuthenticatedUser,
  AutomationSetupField,
  ConnectionStatus,
} from "@/lib/automation";

/* LOGIC EXPLAINED:
This file is the main frontend entry point for the automation flow. The old
logic worked, but it was hard to see whether the prompt was sent, whether the
AI replied, whether integrations loaded, or whether saving failed. The added
logs make each browser step visible in order.
*/

type WorkflowResponse = {
  workflow: {
    name: string;
    description: string;
    trigger: string;
    steps: Array<{
      type: string;
      name: string;
      details: Record<string, string>;
    }>;
    integrations: string[];
    requiredFields: string[];
    setupFields: AutomationSetupField[];
  };
  fieldDefinitions: AutomationSetupField[];
  source: "openai" | "fallback";
};

type IntegrationState = Record<string, ConnectionStatus>;

export default function HeroSection({
  user,
  socialAuthEnabled,
}: {
  user: AuthenticatedUser | null;
  socialAuthEnabled: boolean;
}) {
  const searchParams = useSearchParams();
  const initialPrompt = searchParams.get("prompt") || "";
  const [prompt, setPrompt] = useState(initialPrompt);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [result, setResult] = useState<WorkflowResponse | null>(null);
  const [fieldValues, setFieldValues] = useState<Record<string, string>>({});
  const [integrationStatus, setIntegrationStatus] = useState<IntegrationState>({});
  const [connectionLoading, setConnectionLoading] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const promptRef = useRef<HTMLTextAreaElement>(null);
  const resultRef = useRef<HTMLElement>(null);
  const hasAutoGeneratedRef = useRef(false);
  const { scrollY } = useScroll();
  const heroYRaw = useTransform(scrollY, [0, 280, 700], [0, -16, -40]);
  const heroOpacityRaw = useTransform(scrollY, [0, 600], [1, 0.94]);
  const heroY = useSpring(heroYRaw, {
    stiffness: 88,
    damping: 24,
    mass: 0.55,
  });
  const heroOpacity = useSpring(heroOpacityRaw, {
    stiffness: 90,
    damping: 24,
    mass: 0.55,
  });

  const adjustPromptHeight = useEffectEvent(() => {
    const element = promptRef.current;

    if (!element) {
      return;
    }

    element.style.height = "0px";
    element.style.height = `${Math.min(element.scrollHeight, 260)}px`;
  });

  useEffect(() => {
    adjustPromptHeight();
  }, [prompt]);

  useEffect(() => {
    if (!user) {
      return;
    }

    const loadConnections = async () => {
      try {
        console.log("[HeroSection] Loading integration status for homepage.");
        const response = await fetch("/api/integrations", { cache: "no-store" });

        if (!response.ok) {
          console.log("[HeroSection] Integration preload skipped because response was not ok.");
          return;
        }

        const json = (await response.json()) as {
          integrations?: Array<{
            integration: string;
            status: ConnectionStatus;
          }>;
        };

        const nextStatus: IntegrationState = {};
        (json.integrations ?? []).forEach((integration) => {
          nextStatus[integration.integration] = integration.status;
        });
        setIntegrationStatus(nextStatus);
        console.log("[HeroSection] Integration status loaded.", nextStatus);
      } catch {
        console.error("[HeroSection] Failed to preload integration status.");
        // Best-effort preload for activation.
      }
    };

    void loadConnections();
  }, [user]);

  useEffect(() => {
    if (!result) {
      return;
    }

    const nextValues: Record<string, string> = {};

    result.fieldDefinitions.forEach((field) => {
      nextValues[field.key] = field.type === "select"
        ? field.options?.[0] || ""
        : "";
    });

    setFieldValues(nextValues);
  }, [result]);

  const handleGenerate = async (explicitPrompt?: string) => {
    const nextPrompt = explicitPrompt ?? prompt;
    console.log("[HeroSection] Generate clicked.");
    console.log("[HeroSection] Prompt being sent:", nextPrompt);

    if (!nextPrompt.trim()) {
      console.log("[HeroSection] Generate stopped because prompt was empty.");
      setError("Describe the workflow you want to automate.");
      return;
    }

    setIsGenerating(true);
    setError(null);
    setSuccessMessage(null);

    try {
      const response = await fetch("/api/generate-automation", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt: nextPrompt }),
      });

      const json = (await response.json()) as WorkflowResponse & { error?: string };
      console.log("[HeroSection] Generate response received.", json);

      if (!response.ok) {
        throw new Error(json.error || "Could not generate automation.");
      }

      setResult(json);
      setPrompt(nextPrompt);
      console.log("[HeroSection] Workflow stored in component state.");

      window.requestAnimationFrame(() => {
        resultRef.current?.scrollIntoView({
          behavior: "smooth",
          block: "start",
        });
      });
    } catch (requestError) {
      console.error("[HeroSection] Generate failed.", requestError);
      setError(
        requestError instanceof Error
          ? requestError.message
          : "Could not generate automation.",
      );
    } finally {
      setIsGenerating(false);
    }
  };

  const autoGenerate = useEffectEvent((promptValue: string) => {
    void handleGenerate(promptValue);
  });

  useEffect(() => {
    const shouldAutoGenerate = searchParams.get("autogenerate") === "1";

    if (
      !shouldAutoGenerate ||
      !initialPrompt ||
      hasAutoGeneratedRef.current
    ) {
      return;
    }

    hasAutoGeneratedRef.current = true;
    console.log("[HeroSection] Auto-generate started from URL parameters.");
    autoGenerate(initialPrompt);
  }, [initialPrompt, searchParams]);

  const handleConnectIntegration = async (integration: string) => {
    if (!user) {
      console.log("[HeroSection] Connect blocked because no user is signed in.");
      return;
    }

    console.log("[HeroSection] Connecting integration:", integration);
    setConnectionLoading(integration);
    setError(null);

    try {
      const response = await fetch("/api/integrations/connect", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ integration }),
      });

      const json = (await response.json()) as {
        connection?: { integration: string; status: ConnectionStatus };
        error?: string;
      };
      console.log("[HeroSection] Connect response received.", json);

      if (!response.ok || !json.connection) {
        throw new Error(json.error || "Could not connect integration.");
      }

      setIntegrationStatus((current) => ({
        ...current,
        [json.connection!.integration]: json.connection!.status,
      }));
      console.log("[HeroSection] Integration state updated.");
    } catch (requestError) {
      console.error("[HeroSection] Connect integration failed.", requestError);
      setError(
        requestError instanceof Error
          ? requestError.message
          : "Could not connect integration.",
      );
    } finally {
      setConnectionLoading(null);
    }
  };

  const handleActivate = async () => {
    if (!result || !user) {
      console.log("[HeroSection] Activate blocked because workflow or user is missing.");
      return;
    }

    console.log("[HeroSection] Activate clicked for workflow:", result.workflow.name);
    setIsSaving(true);
    setError(null);
    setSuccessMessage(null);

    try {
      const relevantIntegrationStatus = Object.fromEntries(
        result.workflow.integrations.map((integration) => [
          integration,
          integrationStatus[integration] || "disconnected",
        ]),
      );

      const response = await fetch("/api/save-automation", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          workflow: result.workflow,
          formInputs: fieldValues,
          integrationStatus: relevantIntegrationStatus,
        }),
      });

      const json = (await response.json()) as {
        automation?: { webhookId: string };
        error?: string;
      };
      console.log("[HeroSection] Save response received.", json);

      if (!response.ok || !json.automation) {
        throw new Error(json.error || "Could not activate automation.");
      }

      setSuccessMessage(
        `Automation activated. Webhook path: /api/webhook/${json.automation.webhookId}`,
      );
      console.log("[HeroSection] Automation activated successfully.");
    } catch (requestError) {
      console.error("[HeroSection] Activate failed.", requestError);
      setError(
        requestError instanceof Error
          ? requestError.message
          : "Could not activate automation.",
      );
    } finally {
      setIsSaving(false);
    }
  };

  const allIntegrationsConnected = useMemo(() => {
    if (!result || result.workflow.integrations.length === 0) {
      return true;
    }

    return result.workflow.integrations.every(
      (integration) => integrationStatus[integration] === "connected",
    );
  }, [integrationStatus, result]);

  const resumePath = useMemo(() => {
    const params = new URLSearchParams();

    if (prompt.trim()) {
      params.set("prompt", prompt.trim());
      params.set("autogenerate", "1");
    }

    return params.toString() ? `/?${params.toString()}` : "/";
  }, [prompt]);

  return (
    <>
      <section
        id="home"
        className="relative overflow-hidden bg-background pb-24 pt-28 md:pb-28"
      >
        <HeroScene />

        <motion.div
          style={{ y: heroY, opacity: heroOpacity }}
          className="relative z-10 mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"
        >
          <div className="mx-auto max-w-4xl text-center">
            <div className="inline-flex items-center gap-2 rounded-full border border-black/8 bg-white/85 px-4 py-2 text-xs font-semibold uppercase tracking-[0.24em] text-accent shadow-[0_10px_30px_rgba(28,28,28,0.04)]">
              <Sparkles className="h-4 w-4" />
              AI automation operating system
            </div>

            <h1 className="mt-8 text-[3.6rem] font-semibold leading-[0.98] tracking-[-0.075em] text-foreground sm:text-[4.6rem] lg:text-[5.8rem]">
              Build AI Automations
              <br />
              for Your Business in Minutes
            </h1>

            <p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-foreground/62 sm:text-xl">
              Describe your workflow and our AI will convert it into a real
              automation plan with setup requirements, connected apps, and a
              professional activation flow.
            </p>
          </div>

          <div className="mx-auto mt-14 max-w-5xl">
            <div className="relative overflow-hidden rounded-[2.5rem] border border-black/10 bg-[#18181b] p-3 text-left shadow-[0_34px_90px_rgba(15,23,42,0.18)]">
              <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(255,255,255,0.08),_transparent_28%),linear-gradient(180deg,rgba(255,255,255,0.03),transparent)]" />

              <div className="relative flex flex-col gap-5 rounded-[2rem] border border-white/8 bg-[linear-gradient(180deg,rgba(255,255,255,0.03),rgba(255,255,255,0.01))] px-6 py-6 sm:px-7 sm:py-7">
                <div className="flex items-center justify-between text-[0.95rem] text-white/44">
                  <span>Describe the automation you want...</span>
                  <div className="flex h-8 w-8 items-center justify-center rounded-xl border border-white/10 bg-white/[0.03] text-white/48">
                    +
                  </div>
                </div>

                <textarea
                  ref={promptRef}
                  rows={1}
                  value={prompt}
                  onChange={(event) => setPrompt(event.target.value)}
                  placeholder="Create an automation where when someone fills my Google Form, the form details are sent to my WhatsApp, and the person who filled the form receives an automatic greeting message from my side."
                  className="min-h-[72px] w-full resize-none border-none bg-transparent text-[1.55rem] leading-[1.45] text-white outline-none placeholder:text-white/34 sm:text-[1.8rem]"
                />

                <div className="border-t border-white/7 pt-5">
                  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
                    <div>
                      <p className="text-sm font-medium text-white/45">
                        Example: &quot;Send WhatsApp follow-up when someone fills my
                        form&quot;
                      </p>
                    </div>

                    <button
                      onClick={() => void handleGenerate()}
                      disabled={isGenerating || !prompt.trim()}
                      className="inline-flex h-16 items-center justify-center gap-2 rounded-full border border-white/16 bg-white/7 px-8 text-base font-semibold text-white shadow-[0_12px_32px_rgba(0,0,0,0.16)] transition-all duration-300 hover:-translate-y-0.5 hover:bg-white/11 disabled:cursor-not-allowed disabled:opacity-45"
                    >
                      {isGenerating ? "Generating..." : "Generate Automation"}
                      <ArrowRight className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-8 flex flex-col items-center gap-8">
              <div className="flex flex-wrap items-center justify-center gap-5 text-sm font-medium text-foreground/56 sm:text-base">
                <span className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-foreground" />
                  Fast
                </span>
                <span className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-foreground" />
                  Secure
                </span>
                <span className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-foreground" />
                  No Code Required
                </span>
              </div>

              <div className="flex items-center justify-center">
                {user ? (
                  <Link
                    href="/dashboard"
                    className="inline-flex h-14 items-center justify-center gap-2 rounded-full text-base font-semibold text-foreground/68 transition-colors hover:text-foreground"
                  >
                    Go to Dashboard
                    <ChevronRight className="h-4 w-4" />
                  </Link>
                ) : null}
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      <HomeAutomationPreview
        isGenerating={isGenerating}
        result={result}
        user={user}
        socialAuthEnabled={socialAuthEnabled}
        integrationStatus={integrationStatus}
        connectionLoading={connectionLoading}
        fieldValues={fieldValues}
        error={error}
        successMessage={successMessage}
        isSaving={isSaving}
        allIntegrationsConnected={allIntegrationsConnected}
        resumePath={resumePath}
        resultRef={resultRef}
        onConnectIntegration={handleConnectIntegration}
        onFieldChange={(fieldKey, value) =>
          setFieldValues((current) => ({
            ...current,
            [fieldKey]: value,
          }))
        }
        onActivate={() => void handleActivate()}
      />
    </>
  );
}
